version: '3.7'
services:
    php:
        build: .
        image: php:zend-decoder-5.4
        volumes:
            - ./output:/usr/src/output
            - ./input:/usr/src/input
        command: > 
            bash -c "
            cd Zend-Decoder && 
            php index2.php ../input/logincheck.php > ../output/1.php
            "
