version: '3.7'
services:
    php:
        build: .
        image: php:zend-decoder-5.4
        volumes:
            - ./output:/usr/src/output
            - ./input:/usr/src/input
            # - ./Zend-Decoder:/usr/src/Zend-Decoder
        command: > 
            bash -c "
            cd Zend-Decoder && 
            php decoder.php
            "
